### ISSUE TITLE
放后门的傻逼

### ISSUE THREAD

**Issue by fsquirt** [XiaoBai-12138/OA-EXP#2]
Releases放个后门死了妈

**Comment by fsquirt** [comment]
https://s.threatbook.com/report/file/63d5bf7c121f73b036b0656765810efa6dca3384a19397295d55b797197bfd48

**Comment by XiaoLi996** [comment]
整乐了，我一个写Shell的工具能不报毒？JSP Shell能直接控你Windows？带点脑子
